### ISSUE TITLE
Remove Console.Log, suggestions

### ISSUE THREAD

**Issue by shinho** [Amfeon/PrettyXml#1]
Nice package, finally one working for vue 3.

Some suggestions: 
- It would be nice to remove the console logs from the package. 
- When the node is collapsed, would be nice to have a caret showing that.
- Since the nodes are nodes are not selectable would be nice to have an icon to copy the value to the clipboard.

I'm happy to contribute to this when I find some time.

**Comment by Amfeon** [comment]
Hello. Thank you for bringing up this issue. I've removed the console.log ([commit](https://github.com/Amfeon/PrettyXml/commit/21c14f62b7fd8e6ce70b47779902991ac562301c)). If you would like to improve the functionality, you are welcome to contribute. :)
